const DUMMY_EXPENSES = [
  {
    month: "Abril",
    owner: "Mauri",
    name: "Farmacia DULAC",
    category: "Farmacia",
    description: "Pañales",
    creditCard: "VISA BLACK",
    quota: "1/3",
    price: 30000,
    edit: false,
  },
  {
    month: "Mayo",
    owner: "Pau",
    name: "Claro",
    category: "Factura",
    description: "Abono",
    creditCard: "MASTERCARD BLACK",
    quota: "2/3",
    price: 19000,
    edit: false,
  },
  {
    month: "Mayo",
    owner: "Mauri",
    name: "Supermercado Avellaneda",
    category: "Supermercado",
    description: "Provista",
    creditCard: "MASTERCARD BLACK",
    quota: "1/1",
    price: 75000,
    edit: false,
  },
  {
    month: "Mayo",
    owner: "Ana",
    name: "La Ventana",
    category: "Restaurante",
    description: "Cena",
    creditCard: "VISA GOLD",
    quota: "1/1",
    price: 45000,
    edit: false,
  },
  {
    month: "Mayo",
    owner: "Lucas",
    name: "Apple Store",
    category: "Electrónica",
    description: "iPhone 12",
    creditCard: "AMEX PLATINUM",
    quota: "1/12",
    price: 120000,
    edit: false,
  },
  {
    month: "Marzo",
    owner: "Carla",
    name: "Cine Hoyts",
    category: "Entretenimiento",
    description: "Entradas cine",
    creditCard: "VISA BLACK",
    quota: "1/1",
    price: 15000,
    edit: false,
  },
  {
    month: "Febrero",
    owner: "Sofía",
    name: "Zara",
    category: "Ropa",
    description: "Chaqueta",
    creditCard: "MASTERCARD SILVER",
    quota: "1/4",
    price: 80000,
    edit: false,
  },
];

export default DUMMY_EXPENSES;
